---
- name: Install Kerberos and LDAP clients
  become: true
  yum:
    name:
      - krb5-workstation
      - openldap-clients
    state: present

- name: Create Kerberos config
  become: true
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
